//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.Dashboard.tx
{


    public partial class cardhistory
    {

        /// <summary>
        /// divCardFilter control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCardFilter;

        /// <summary>
        /// rptGroups control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptGroups;

        /// <summary>
        /// divNoFeed control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divNoFeed;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new QryptoCard.Dashboard.SiteMaster Master
        {
            get
            {
                return ((QryptoCard.Dashboard.SiteMaster)(base.Master));
            }
        }
    }
}
