//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.API.Scheduler.SchedulerV1Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchedulerV1Service.ISchedulerV1Service")]
    public interface ISchedulerV1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchedulerV1Service/checkExpiredTransaction", ReplyAction="http://tempuri.org/ISchedulerV1Service/checkExpiredTransactionResponse")]
        void checkExpiredTransaction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchedulerV1Service/checkExpiredTransaction", ReplyAction="http://tempuri.org/ISchedulerV1Service/checkExpiredTransactionResponse")]
        System.Threading.Tasks.Task checkExpiredTransactionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchedulerV1ServiceChannel : QryptoCard.API.Scheduler.SchedulerV1Service.ISchedulerV1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulerV1ServiceClient : System.ServiceModel.ClientBase<QryptoCard.API.Scheduler.SchedulerV1Service.ISchedulerV1Service>, QryptoCard.API.Scheduler.SchedulerV1Service.ISchedulerV1Service {
        
        public SchedulerV1ServiceClient() {
        }
        
        public SchedulerV1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulerV1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerV1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerV1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void checkExpiredTransaction() {
            base.Channel.checkExpiredTransaction();
        }
        
        public System.Threading.Tasks.Task checkExpiredTransactionAsync() {
            return base.Channel.checkExpiredTransactionAsync();
        }
    }
}
