//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.Dashboard.card
{
    public partial class fundingstatus
    {
    }
}
