//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.API.Admin.DashboardV1Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DashboardAdminModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    public partial class DashboardAdminModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalDepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalUsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCards {
            get {
                return this.TotalCardsField;
            }
            set {
                if ((this.TotalCardsField.Equals(value) != true)) {
                    this.TotalCardsField = value;
                    this.RaisePropertyChanged("TotalCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalDeposit {
            get {
                return this.TotalDepositField;
            }
            set {
                if ((this.TotalDepositField.Equals(value) != true)) {
                    this.TotalDepositField = value;
                    this.RaisePropertyChanged("TotalDeposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUsers {
            get {
                return this.TotalUsersField;
            }
            set {
                if ((this.TotalUsersField.Equals(value) != true)) {
                    this.TotalUsersField = value;
                    this.RaisePropertyChanged("TotalUsers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.DashboardV1Service.DashboardAdminModel))]
    public partial class OutputModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DashboardV1Service.IDashboardV1Service")]
    public interface IDashboardV1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardV1Service/getDashboardData", ReplyAction="http://tempuri.org/IDashboardV1Service/getDashboardDataResponse")]
        QryptoCard.API.Admin.DashboardV1Service.OutputModel getDashboardData(string em, QryptoCard.API.Admin.DashboardV1Service.DashboardAdminModel a);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardV1Service/getDashboardData", ReplyAction="http://tempuri.org/IDashboardV1Service/getDashboardDataResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.DashboardV1Service.OutputModel> getDashboardDataAsync(string em, QryptoCard.API.Admin.DashboardV1Service.DashboardAdminModel a);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardV1Service/get10ActiveCardTransaction", ReplyAction="http://tempuri.org/IDashboardV1Service/get10ActiveCardTransactionResponse")]
        QryptoCard.API.Admin.DashboardV1Service.OutputModel get10ActiveCardTransaction(string em);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardV1Service/get10ActiveCardTransaction", ReplyAction="http://tempuri.org/IDashboardV1Service/get10ActiveCardTransactionResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.DashboardV1Service.OutputModel> get10ActiveCardTransactionAsync(string em);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDashboardV1ServiceChannel : QryptoCard.API.Admin.DashboardV1Service.IDashboardV1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DashboardV1ServiceClient : System.ServiceModel.ClientBase<QryptoCard.API.Admin.DashboardV1Service.IDashboardV1Service>, QryptoCard.API.Admin.DashboardV1Service.IDashboardV1Service {
        
        public DashboardV1ServiceClient() {
        }
        
        public DashboardV1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DashboardV1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardV1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardV1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QryptoCard.API.Admin.DashboardV1Service.OutputModel getDashboardData(string em, QryptoCard.API.Admin.DashboardV1Service.DashboardAdminModel a) {
            return base.Channel.getDashboardData(em, a);
        }

        public System.Threading.Tasks.Task<QryptoCard.API.Admin.DashboardV1Service.OutputModel> getDashboardDataAsync(string em, QryptoCard.API.Admin.DashboardV1Service.DashboardAdminModel a) {
            return base.Channel.getDashboardDataAsync(em, a);
        }

        public QryptoCard.API.Admin.DashboardV1Service.OutputModel get10ActiveCardTransaction(string em) {
            return base.Channel.get10ActiveCardTransaction(em);
        }

        public System.Threading.Tasks.Task<QryptoCard.API.Admin.DashboardV1Service.OutputModel> get10ActiveCardTransactionAsync(string em) {
            return base.Channel.get10ActiveCardTransactionAsync(em);
        }
    }
}
