//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.Dashboard
{


    public partial class dashboard
    {

        /// <summary>
        /// hfReferralCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfReferralCode;

        /// <summary>
        /// hfReferralLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfReferralLink;

        /// <summary>
        /// lblBalance control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblBalance;

        /// <summary>
        /// viewCard control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl viewCard;

        /// <summary>
        /// card3dWrap control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl card3dWrap;

        /// <summary>
        /// lblCardNetwork control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblCardNetwork;

        /// <summary>
        /// lblCardLast4 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblCardLast4;

        /// <summary>
        /// lblCardExp control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblCardExp;

        /// <summary>
        /// lnkCardDetails control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkCardDetails;

        /// <summary>
        /// viewNoCard control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl viewNoCard;

        /// <summary>
        /// divNoLedger control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divNoLedger;

        /// <summary>
        /// rptLedger control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptLedger;

        /// <summary>
        /// ledgerPager control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ledgerPager;

        /// <summary>
        /// lblCommissionRate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblCommissionRate;

        /// <summary>
        /// lblTotalCommission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTotalCommission;

        /// <summary>
        /// lblTotalCards control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTotalCards;

        /// <summary>
        /// txtReferralCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtReferralCode;

        /// <summary>
        /// btnCopyReferralCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCopyReferralCode;

        /// <summary>
        /// txtReferralLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtReferralLink;

        /// <summary>
        /// btnCopyReferralLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCopyReferralLink;

        /// <summary>
        /// divnoreferral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divnoreferral;

        /// <summary>
        /// Label2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;

        /// <summary>
        /// gvReferralList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvReferralList;

        /// <summary>
        /// divnocommission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divnocommission;

        /// <summary>
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new QryptoCard.Dashboard.SiteMaster Master
        {
            get
            {
                return ((QryptoCard.Dashboard.SiteMaster)(base.Master));
            }
        }
    }
}
