//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.Dashboard
{


    public partial class referrals
    {

        /// <summary>
        /// hfReferralCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfReferralCode;

        /// <summary>
        /// hfReferralLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfReferralLink;

        /// <summary>
        /// txtReferralCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReferralCode;

        /// <summary>
        /// btnCopyReferralCode control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCopyReferralCode;

        /// <summary>
        /// txtReferralLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReferralLink;

        /// <summary>
        /// btnCopyReferralLink control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCopyReferralLink;

        /// <summary>
        /// lblCommissionRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal lblCommissionRate;

        /// <summary>
        /// lblTotalCommission control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal lblTotalCommission;

        /// <summary>
        /// lblTotalReferrals control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal lblTotalReferrals;

        /// <summary>pnlAvailBal control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAvailBal;

        /// <summary>lblAvailBalance control.</summary>
        protected global::System.Web.UI.WebControls.Literal lblAvailBalance;

        /// <summary>
        /// divnoreferral control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divnoreferral;

        /// <summary>
        /// lblNoReferral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoReferral;

        /// <summary>
        /// gvReferralList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvReferralList;

        /// <summary>
        /// divnocommission control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divnocommission;

        /// <summary>
        /// lblNoCommission control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoCommission;

        /// <summary>
        /// gvCommissionList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvCommissionList;

        /// <summary>
        /// Master property.
        /// </summary>
        public new QryptoCard.Dashboard.SiteMaster Master
        {
            get
            {
                return ((QryptoCard.Dashboard.SiteMaster)(base.Master));
            }
        }
    }
}
