//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.Dashboard
{
    public partial class settings
    {
        /// <summary>hfEmailOtpId control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEmailOtpId;

        /// <summary>hfNewEmail control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfNewEmail;

        /// <summary>pnlMsg control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>lblMsg control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMsg;

        /// <summary>txtFirstName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>txtLastName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>btnSaveProfile control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;

        /// <summary>txtCurrentEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentEmail;

        /// <summary>txtNewEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewEmail;

        /// <summary>btnSendEmailOtp control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSendEmailOtp;

        /// <summary>pnlEmailOtp control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmailOtp;

        /// <summary>txtEmailOtp control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmailOtp;

        /// <summary>btnConfirmEmail control.</summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmEmail;

        /// <summary>txtCurrentPw control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPw;

        /// <summary>txtNewPw control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPw;

        /// <summary>txtConfirmPw control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPw;

        /// <summary>btnChangePw control.</summary>
        protected global::System.Web.UI.WebControls.Button btnChangePw;

        /// <summary>txtReferralCode control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtReferralCode;

        /// <summary>txtReferralLink control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtReferralLink;

        /// <summary>
        /// Master property. Strongly-typed accessor generated for the MasterType directive,
        /// so the code-behind can call SiteMaster.checkCookies()/forceLogin().
        /// </summary>
        public new QryptoCard.Dashboard.SiteMaster Master
        {
            get
            {
                return ((QryptoCard.Dashboard.SiteMaster)(base.Master));
            }
        }
    }
}
