//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.API.Callback.CallbackV1Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PGCryptoModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Callback.Model.PGCrypto")]
    [System.SerializableAttribute()]
    public partial class PGCryptoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoinIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CommisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CommisionInPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetworkTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coin {
            get {
                return this.CoinField;
            }
            set {
                if ((object.ReferenceEquals(this.CoinField, value) != true)) {
                    this.CoinField = value;
                    this.RaisePropertyChanged("Coin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoinID {
            get {
                return this.CoinIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CoinIDField, value) != true)) {
                    this.CoinIDField = value;
                    this.RaisePropertyChanged("CoinID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Commision {
            get {
                return this.CommisionField;
            }
            set {
                if ((this.CommisionField.Equals(value) != true)) {
                    this.CommisionField = value;
                    this.RaisePropertyChanged("Commision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CommisionInPercentage {
            get {
                return this.CommisionInPercentageField;
            }
            set {
                if ((this.CommisionInPercentageField.Equals(value) != true)) {
                    this.CommisionInPercentageField = value;
                    this.RaisePropertyChanged("CommisionInPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateExpired {
            get {
                return this.DateExpiredField;
            }
            set {
                if ((this.DateExpiredField.Equals(value) != true)) {
                    this.DateExpiredField = value;
                    this.RaisePropertyChanged("DateExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetworkType {
            get {
                return this.NetworkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NetworkTypeField, value) != true)) {
                    this.NetworkTypeField = value;
                    this.RaisePropertyChanged("NetworkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerReferenceID {
            get {
                return this.PartnerReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerReferenceIDField, value) != true)) {
                    this.PartnerReferenceIDField = value;
                    this.RaisePropertyChanged("PartnerReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeField, value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptURL {
            get {
                return this.ReceiptURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptURLField, value) != true)) {
                    this.ReceiptURLField = value;
                    this.RaisePropertyChanged("ReceiptURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenID {
            get {
                return this.TokenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenIDField, value) != true)) {
                    this.TokenIDField = value;
                    this.RaisePropertyChanged("TokenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isPaid {
            get {
                return this.isPaidField;
            }
            set {
                if ((this.isPaidField.Equals(value) != true)) {
                    this.isPaidField = value;
                    this.RaisePropertyChanged("isPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isToken {
            get {
                return this.isTokenField;
            }
            set {
                if ((this.isTokenField.Equals(value) != true)) {
                    this.isTokenField = value;
                    this.RaisePropertyChanged("isToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CallbackV1Service.ICallbackV1Service")]
    public interface ICallbackV1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/testDecrypt", ReplyAction="http://tempuri.org/ICallbackV1Service/testDecryptResponse")]
        string testDecrypt(string x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/testDecrypt", ReplyAction="http://tempuri.org/ICallbackV1Service/testDecryptResponse")]
        System.Threading.Tasks.Task<string> testDecryptAsync(string x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/Wasabi", ReplyAction="http://tempuri.org/ICallbackV1Service/WasabiResponse")]
        void Wasabi(string cat, string sign, string req, string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/Wasabi", ReplyAction="http://tempuri.org/ICallbackV1Service/WasabiResponse")]
        System.Threading.Tasks.Task WasabiAsync(string cat, string sign, string req, string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/PGCrypto", ReplyAction="http://tempuri.org/ICallbackV1Service/PGCryptoResponse")]
        void PGCrypto(QryptoCard.API.Callback.CallbackV1Service.PGCryptoModel x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/PGCrypto", ReplyAction="http://tempuri.org/ICallbackV1Service/PGCryptoResponse")]
        System.Threading.Tasks.Task PGCryptoAsync(QryptoCard.API.Callback.CallbackV1Service.PGCryptoModel x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/recreateCallback", ReplyAction="http://tempuri.org/ICallbackV1Service/recreateCallbackResponse")]
        void recreateCallback();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/recreateCallback", ReplyAction="http://tempuri.org/ICallbackV1Service/recreateCallbackResponse")]
        System.Threading.Tasks.Task recreateCallbackAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/reTopup", ReplyAction="http://tempuri.org/ICallbackV1Service/reTopupResponse")]
        void reTopup(string tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/reTopup", ReplyAction="http://tempuri.org/ICallbackV1Service/reTopupResponse")]
        System.Threading.Tasks.Task reTopupAsync(string tid);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/ReconcilePendingProvider", ReplyAction="http://tempuri.org/ICallbackV1Service/ReconcilePendingProviderResponse")]
        int ReconcilePendingProvider();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/ReconcilePendingProvider", ReplyAction="http://tempuri.org/ICallbackV1Service/ReconcilePendingProviderResponse")]
        System.Threading.Tasks.Task<int> ReconcilePendingProviderAsync();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/RunWasabiCardMonitor", ReplyAction="http://tempuri.org/ICallbackV1Service/RunWasabiCardMonitorResponse")]
        string RunWasabiCardMonitor();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/RunWasabiCardMonitor", ReplyAction="http://tempuri.org/ICallbackV1Service/RunWasabiCardMonitorResponse")]
        System.Threading.Tasks.Task<string> RunWasabiCardMonitorAsync();

        // Hand-added to mirror RunWasabiCardMonitor (deposit-into-card pump tick). Regenerate the
        // service reference in VS to normalize this file when convenient.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/RunCardFundingPump", ReplyAction="http://tempuri.org/ICallbackV1Service/RunCardFundingPumpResponse")]
        string RunCardFundingPump();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallbackV1Service/RunCardFundingPump", ReplyAction="http://tempuri.org/ICallbackV1Service/RunCardFundingPumpResponse")]
        System.Threading.Tasks.Task<string> RunCardFundingPumpAsync();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICallbackV1ServiceChannel : QryptoCard.API.Callback.CallbackV1Service.ICallbackV1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallbackV1ServiceClient : System.ServiceModel.ClientBase<QryptoCard.API.Callback.CallbackV1Service.ICallbackV1Service>, QryptoCard.API.Callback.CallbackV1Service.ICallbackV1Service {
        
        public CallbackV1ServiceClient() {
        }
        
        public CallbackV1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallbackV1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallbackV1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallbackV1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string testDecrypt(string x) {
            return base.Channel.testDecrypt(x);
        }
        
        public System.Threading.Tasks.Task<string> testDecryptAsync(string x) {
            return base.Channel.testDecryptAsync(x);
        }
        
        public void Wasabi(string cat, string sign, string req, string a) {
            base.Channel.Wasabi(cat, sign, req, a);
        }
        
        public System.Threading.Tasks.Task WasabiAsync(string cat, string sign, string req, string a) {
            return base.Channel.WasabiAsync(cat, sign, req, a);
        }
        
        public void PGCrypto(QryptoCard.API.Callback.CallbackV1Service.PGCryptoModel x) {
            base.Channel.PGCrypto(x);
        }
        
        public System.Threading.Tasks.Task PGCryptoAsync(QryptoCard.API.Callback.CallbackV1Service.PGCryptoModel x) {
            return base.Channel.PGCryptoAsync(x);
        }
        
        public void recreateCallback() {
            base.Channel.recreateCallback();
        }
        
        public System.Threading.Tasks.Task recreateCallbackAsync() {
            return base.Channel.recreateCallbackAsync();
        }
        
        public void reTopup(string tid) {
            base.Channel.reTopup(tid);
        }

        public System.Threading.Tasks.Task reTopupAsync(string tid) {
            return base.Channel.reTopupAsync(tid);
        }

        public int ReconcilePendingProvider() {
            return base.Channel.ReconcilePendingProvider();
        }

        public System.Threading.Tasks.Task<int> ReconcilePendingProviderAsync() {
            return base.Channel.ReconcilePendingProviderAsync();
        }

        public string RunWasabiCardMonitor() {
            return base.Channel.RunWasabiCardMonitor();
        }

        public System.Threading.Tasks.Task<string> RunWasabiCardMonitorAsync() {
            return base.Channel.RunWasabiCardMonitorAsync();
        }

        public string RunCardFundingPump() {
            return base.Channel.RunCardFundingPump();
        }

        public System.Threading.Tasks.Task<string> RunCardFundingPumpAsync() {
            return base.Channel.RunCardFundingPumpAsync();
        }
    }
}
