//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblH_Admin_Login> tblH_Admin_Login { get; set; }
        public virtual DbSet<tblH_Admin_OTP> tblH_Admin_OTP { get; set; }
        public virtual DbSet<tblH_API_Log> tblH_API_Log { get; set; }
        public virtual DbSet<tblH_Partner_Webhook> tblH_Partner_Webhook { get; set; }
        public virtual DbSet<tblH_Partner_Webhook_ID> tblH_Partner_Webhook_ID { get; set; }
        public virtual DbSet<tblH_User_Balance> tblH_User_Balance { get; set; }
        public virtual DbSet<tblH_User_Login> tblH_User_Login { get; set; }
        public virtual DbSet<tblH_User_OTP> tblH_User_OTP { get; set; }
        public virtual DbSet<tblH_User_Register> tblH_User_Register { get; set; }
        public virtual DbSet<tblM_Address_Generator> tblM_Address_Generator { get; set; }
        public virtual DbSet<tblM_Admin> tblM_Admin { get; set; }
        public virtual DbSet<tblM_Admin_Role> tblM_Admin_Role { get; set; }
        public virtual DbSet<tblM_Card_Type> tblM_Card_Type { get; set; }
        public virtual DbSet<tblM_Card_Type_Recharge> tblM_Card_Type_Recharge { get; set; }
        public virtual DbSet<tblM_Cardholder> tblM_Cardholder { get; set; }
        public virtual DbSet<tblM_Country_City> tblM_Country_City { get; set; }
        public virtual DbSet<tblM_Country_Mobile> tblM_Country_Mobile { get; set; }
        public virtual DbSet<tblM_Country_Region> tblM_Country_Region { get; set; }
        public virtual DbSet<tblM_Crypto_Network> tblM_Crypto_Network { get; set; }
        public virtual DbSet<tblM_Setting> tblM_Setting { get; set; }
        public virtual DbSet<tblM_Setting_Counter> tblM_Setting_Counter { get; set; }
        public virtual DbSet<tblM_User> tblM_User { get; set; }
        public virtual DbSet<tblM_User_2FA> tblM_User_2FA { get; set; }
        public virtual DbSet<tblM_User_API> tblM_User_API { get; set; }
        public virtual DbSet<tblM_User_Balance> tblM_User_Balance { get; set; }
        public virtual DbSet<tblM_User_Commission> tblM_User_Commission { get; set; }
        public virtual DbSet<tblM_User_Crypto_Deposit> tblM_User_Crypto_Deposit { get; set; }
        public virtual DbSet<tblM_User_Fee> tblM_User_Fee { get; set; }
        public virtual DbSet<tblM_User_Referral> tblM_User_Referral { get; set; }
        public virtual DbSet<tblM_User_Role> tblM_User_Role { get; set; }
        public virtual DbSet<tblT_Admin_ForgotPassword> tblT_Admin_ForgotPassword { get; set; }
        public virtual DbSet<tblT_Card> tblT_Card { get; set; }
        public virtual DbSet<tblT_Card_Balance> tblT_Card_Balance { get; set; }
        public virtual DbSet<tblT_Card_Deposit> tblT_Card_Deposit { get; set; }
        public virtual DbSet<tblT_Card_Transaction> tblT_Card_Transaction { get; set; }
        public virtual DbSet<tblT_Card_Transaction_Auth> tblT_Card_Transaction_Auth { get; set; }
        public virtual DbSet<tblT_Commission> tblT_Commission { get; set; }
        public virtual DbSet<tblT_User_ForgotPassword> tblT_User_ForgotPassword { get; set; }
        public virtual DbSet<vw_Admin> vw_Admin { get; set; }
        public virtual DbSet<vw_Card> vw_Card { get; set; }
        public virtual DbSet<vw_Card_Deposit> vw_Card_Deposit { get; set; }
        public virtual DbSet<vw_User_Commission> vw_User_Commission { get; set; }
        public virtual DbSet<vw_User_Fee> vw_User_Fee { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
