//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_User_API
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string APIKey { get; set; }
        public string SecretKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string CallbackURL { get; set; }
        public string CallbackSigningKey { get; set; }
    }
}
