//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_Card_Transaction
    {
        public long ID { get; set; }
        public string CardNo { get; set; }
        public string TradeNo { get; set; }
        public string OriginTradeNo { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> AuthorizedAmount { get; set; }
        public string AuthorizedCurrency { get; set; }
        public Nullable<double> Fee { get; set; }
        public string FeeCurrency { get; set; }
        public Nullable<double> CrossBoardFee { get; set; }
        public string CrossBoardFeeCurrency { get; set; }
        public Nullable<double> SettleAmount { get; set; }
        public string SettleCurrency { get; set; }
        public Nullable<System.DateTime> SettleDate { get; set; }
        public string MerchantName { get; set; }
        public string Type { get; set; }
        public string TypeStr { get; set; }
        public string Status { get; set; }
        public string StatusStr { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public string Payload { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
    }
}
