//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_Card
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public Nullable<long> CardTypeId { get; set; }
        public string OrderNo { get; set; }
        public Nullable<long> HolderID { get; set; }
        public string CardNo { get; set; }
        public string CardNumber { get; set; }
        public string CVV { get; set; }
        public string ValidPeriod { get; set; }
        public string Currency { get; set; }
        public Nullable<double> BaseFee { get; set; }
        public Nullable<double> BaseAmount { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> InitialDeposit { get; set; }
        public Nullable<double> Fee { get; set; }
        public Nullable<double> FeeInPercentage { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> ReceivedAmount { get; set; }
        public string ReceivedCurrency { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> isNeedCardholder { get; set; }
        public string AddressID { get; set; }
        public string Address { get; set; }
        public string ReceiptURL { get; set; }
        public string Txhash { get; set; }
        public string PGCryptoID { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
        public string Param4 { get; set; }
        public string Param5 { get; set; }
        public string UserReferenceID { get; set; }
    }
}
