//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.API.Admin.CardV1Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblM_Card_Type", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class tblM_Card_Type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankCardBinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPriceCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CardTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepositAmountMaxQuotaForActiveCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepositAmountMinQuotaForActiveCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FiatCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NeedCardHolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NeedDepositForActiveCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalCardPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalCardPriceCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalRechargeFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalRechargeFeeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RechargeFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RechargeFeeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RechargeMaxQuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RechargeMinQuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupportHolderAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupportHolderReginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCardBin {
            get {
                return this.BankCardBinField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCardBinField, value) != true)) {
                    this.BankCardBinField = value;
                    this.RaisePropertyChanged("BankCardBin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardDesc {
            get {
                return this.CardDescField;
            }
            set {
                if ((object.ReferenceEquals(this.CardDescField, value) != true)) {
                    this.CardDescField = value;
                    this.RaisePropertyChanged("CardDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPrice {
            get {
                return this.CardPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPriceField, value) != true)) {
                    this.CardPriceField = value;
                    this.RaisePropertyChanged("CardPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPriceCurrency {
            get {
                return this.CardPriceCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPriceCurrencyField, value) != true)) {
                    this.CardPriceCurrencyField = value;
                    this.RaisePropertyChanged("CardPriceCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CardTypeId {
            get {
                return this.CardTypeIdField;
            }
            set {
                if ((this.CardTypeIdField.Equals(value) != true)) {
                    this.CardTypeIdField = value;
                    this.RaisePropertyChanged("CardTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepositAmountMaxQuotaForActiveCard {
            get {
                return this.DepositAmountMaxQuotaForActiveCardField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositAmountMaxQuotaForActiveCardField, value) != true)) {
                    this.DepositAmountMaxQuotaForActiveCardField = value;
                    this.RaisePropertyChanged("DepositAmountMaxQuotaForActiveCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepositAmountMinQuotaForActiveCard {
            get {
                return this.DepositAmountMinQuotaForActiveCardField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositAmountMinQuotaForActiveCardField, value) != true)) {
                    this.DepositAmountMinQuotaForActiveCardField = value;
                    this.RaisePropertyChanged("DepositAmountMinQuotaForActiveCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FiatCurrency {
            get {
                return this.FiatCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.FiatCurrencyField, value) != true)) {
                    this.FiatCurrencyField = value;
                    this.RaisePropertyChanged("FiatCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxCount {
            get {
                return this.MaxCountField;
            }
            set {
                if ((this.MaxCountField.Equals(value) != true)) {
                    this.MaxCountField = value;
                    this.RaisePropertyChanged("MaxCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NeedCardHolder {
            get {
                return this.NeedCardHolderField;
            }
            set {
                if ((this.NeedCardHolderField.Equals(value) != true)) {
                    this.NeedCardHolderField = value;
                    this.RaisePropertyChanged("NeedCardHolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NeedDepositForActiveCard {
            get {
                return this.NeedDepositForActiveCardField;
            }
            set {
                if ((this.NeedDepositForActiveCardField.Equals(value) != true)) {
                    this.NeedDepositForActiveCardField = value;
                    this.RaisePropertyChanged("NeedDepositForActiveCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalCardPrice {
            get {
                return this.OriginalCardPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalCardPriceField, value) != true)) {
                    this.OriginalCardPriceField = value;
                    this.RaisePropertyChanged("OriginalCardPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalCardPriceCurrency {
            get {
                return this.OriginalCardPriceCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalCardPriceCurrencyField, value) != true)) {
                    this.OriginalCardPriceCurrencyField = value;
                    this.RaisePropertyChanged("OriginalCardPriceCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalRechargeFee {
            get {
                return this.OriginalRechargeFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalRechargeFeeField, value) != true)) {
                    this.OriginalRechargeFeeField = value;
                    this.RaisePropertyChanged("OriginalRechargeFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalRechargeFeeRate {
            get {
                return this.OriginalRechargeFeeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalRechargeFeeRateField, value) != true)) {
                    this.OriginalRechargeFeeRateField = value;
                    this.RaisePropertyChanged("OriginalRechargeFeeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechargeFee {
            get {
                return this.RechargeFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.RechargeFeeField, value) != true)) {
                    this.RechargeFeeField = value;
                    this.RaisePropertyChanged("RechargeFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechargeFeeRate {
            get {
                return this.RechargeFeeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.RechargeFeeRateField, value) != true)) {
                    this.RechargeFeeRateField = value;
                    this.RaisePropertyChanged("RechargeFeeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechargeMaxQuota {
            get {
                return this.RechargeMaxQuotaField;
            }
            set {
                if ((object.ReferenceEquals(this.RechargeMaxQuotaField, value) != true)) {
                    this.RechargeMaxQuotaField = value;
                    this.RaisePropertyChanged("RechargeMaxQuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechargeMinQuota {
            get {
                return this.RechargeMinQuotaField;
            }
            set {
                if ((object.ReferenceEquals(this.RechargeMinQuotaField, value) != true)) {
                    this.RechargeMinQuotaField = value;
                    this.RaisePropertyChanged("RechargeMinQuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Support {
            get {
                return this.SupportField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportField, value) != true)) {
                    this.SupportField = value;
                    this.RaisePropertyChanged("Support");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportHolderAreaCode {
            get {
                return this.SupportHolderAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportHolderAreaCodeField, value) != true)) {
                    this.SupportHolderAreaCodeField = value;
                    this.RaisePropertyChanged("SupportHolderAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportHolderRegin {
            get {
                return this.SupportHolderReginField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportHolderReginField, value) != true)) {
                    this.SupportHolderReginField = value;
                    this.RaisePropertyChanged("SupportHolderRegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeStr {
            get {
                return this.TypeStrField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeStrField, value) != true)) {
                    this.TypeStrField = value;
                    this.RaisePropertyChanged("TypeStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.CardV1Service.vw_Card))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.CardV1Service.CardFilterModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.CardV1Service.DepositFilterModel))]
    public partial class OutputModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_Card", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class vw_Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CardTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> FeeInPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HolderAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> HolderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> InitialDepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalRechargeFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalRechargeFeeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ReceivedAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivedCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RechargeFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RechargeFeeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isNeedCardholderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressIDField, value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdayField, value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardDesc {
            get {
                return this.CardDescField;
            }
            set {
                if ((object.ReferenceEquals(this.CardDescField, value) != true)) {
                    this.CardDescField = value;
                    this.RaisePropertyChanged("CardDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CardTypeId {
            get {
                return this.CardTypeIdField;
            }
            set {
                if ((this.CardTypeIdField.Equals(value) != true)) {
                    this.CardTypeIdField = value;
                    this.RaisePropertyChanged("CardTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryStr {
            get {
                return this.CountryStrField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryStrField, value) != true)) {
                    this.CountryStrField = value;
                    this.RaisePropertyChanged("CountryStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateExpired {
            get {
                return this.DateExpiredField;
            }
            set {
                if ((this.DateExpiredField.Equals(value) != true)) {
                    this.DateExpiredField = value;
                    this.RaisePropertyChanged("DateExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateModified {
            get {
                return this.DateModifiedField;
            }
            set {
                if ((this.DateModifiedField.Equals(value) != true)) {
                    this.DateModifiedField = value;
                    this.RaisePropertyChanged("DateModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FeeInPercentage {
            get {
                return this.FeeInPercentageField;
            }
            set {
                if ((this.FeeInPercentageField.Equals(value) != true)) {
                    this.FeeInPercentageField = value;
                    this.RaisePropertyChanged("FeeInPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HolderAddress {
            get {
                return this.HolderAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HolderAddressField, value) != true)) {
                    this.HolderAddressField = value;
                    this.RaisePropertyChanged("HolderAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> HolderID {
            get {
                return this.HolderIDField;
            }
            set {
                if ((this.HolderIDField.Equals(value) != true)) {
                    this.HolderIDField = value;
                    this.RaisePropertyChanged("HolderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> InitialDeposit {
            get {
                return this.InitialDepositField;
            }
            set {
                if ((this.InitialDepositField.Equals(value) != true)) {
                    this.InitialDepositField = value;
                    this.RaisePropertyChanged("InitialDeposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalRechargeFee {
            get {
                return this.OriginalRechargeFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalRechargeFeeField, value) != true)) {
                    this.OriginalRechargeFeeField = value;
                    this.RaisePropertyChanged("OriginalRechargeFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalRechargeFeeRate {
            get {
                return this.OriginalRechargeFeeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalRechargeFeeRateField, value) != true)) {
                    this.OriginalRechargeFeeRateField = value;
                    this.RaisePropertyChanged("OriginalRechargeFeeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3 {
            get {
                return this.Param3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param3Field, value) != true)) {
                    this.Param3Field = value;
                    this.RaisePropertyChanged("Param3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param4 {
            get {
                return this.Param4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param4Field, value) != true)) {
                    this.Param4Field = value;
                    this.RaisePropertyChanged("Param4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param5 {
            get {
                return this.Param5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param5Field, value) != true)) {
                    this.Param5Field = value;
                    this.RaisePropertyChanged("Param5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ReceivedAmount {
            get {
                return this.ReceivedAmountField;
            }
            set {
                if ((this.ReceivedAmountField.Equals(value) != true)) {
                    this.ReceivedAmountField = value;
                    this.RaisePropertyChanged("ReceivedAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivedCurrency {
            get {
                return this.ReceivedCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivedCurrencyField, value) != true)) {
                    this.ReceivedCurrencyField = value;
                    this.RaisePropertyChanged("ReceivedCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechargeFee {
            get {
                return this.RechargeFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.RechargeFeeField, value) != true)) {
                    this.RechargeFeeField = value;
                    this.RaisePropertyChanged("RechargeFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechargeFeeRate {
            get {
                return this.RechargeFeeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.RechargeFeeRateField, value) != true)) {
                    this.RechargeFeeRateField = value;
                    this.RaisePropertyChanged("RechargeFeeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateStr {
            get {
                return this.StateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.StateStrField, value) != true)) {
                    this.StateStrField = value;
                    this.RaisePropertyChanged("StateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Support {
            get {
                return this.SupportField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportField, value) != true)) {
                    this.SupportField = value;
                    this.RaisePropertyChanged("Support");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TownStr {
            get {
                return this.TownStrField;
            }
            set {
                if ((object.ReferenceEquals(this.TownStrField, value) != true)) {
                    this.TownStrField = value;
                    this.RaisePropertyChanged("TownStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidPeriod {
            get {
                return this.ValidPeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidPeriodField, value) != true)) {
                    this.ValidPeriodField = value;
                    this.RaisePropertyChanged("ValidPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isNeedCardholder {
            get {
                return this.isNeedCardholderField;
            }
            set {
                if ((this.isNeedCardholderField.Equals(value) != true)) {
                    this.isNeedCardholderField = value;
                    this.RaisePropertyChanged("isNeedCardholder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardFilterModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    public partial class CardFilterModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardTypeId {
            get {
                return this.CardTypeIdField;
            }
            set {
                if ((this.CardTypeIdField.Equals(value) != true)) {
                    this.CardTypeIdField = value;
                    this.RaisePropertyChanged("CardTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepositFilterModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    public partial class DepositFilterModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardTypeId {
            get {
                return this.CardTypeIdField;
            }
            set {
                if ((this.CardTypeIdField.Equals(value) != true)) {
                    this.CardTypeIdField = value;
                    this.RaisePropertyChanged("CardTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CardV1Service.ICardV1Service")]
    public interface ICardV1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/CardType", ReplyAction="http://tempuri.org/ICardV1Service/CardTypeResponse")]
        QryptoCard.API.Admin.CardV1Service.OutputModel CardType(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/CardType", ReplyAction="http://tempuri.org/ICardV1Service/CardTypeResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> CardTypeAsync(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getCardTypeById", ReplyAction="http://tempuri.org/ICardV1Service/getCardTypeByIdResponse")]
        QryptoCard.API.Admin.CardV1Service.OutputModel getCardTypeById(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getCardTypeById", ReplyAction="http://tempuri.org/ICardV1Service/getCardTypeByIdResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getCardTypeByIdAsync(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getActiveCard", ReplyAction="http://tempuri.org/ICardV1Service/getActiveCardResponse")]
        QryptoCard.API.Admin.CardV1Service.OutputModel getActiveCard(string em);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getActiveCard", ReplyAction="http://tempuri.org/ICardV1Service/getActiveCardResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getActiveCardAsync(string em);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getCardListAll", ReplyAction="http://tempuri.org/ICardV1Service/getCardListAllResponse")]
        QryptoCard.API.Admin.CardV1Service.OutputModel getCardListAll(string em, QryptoCard.API.Admin.CardV1Service.vw_Card x);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getCardListAll", ReplyAction="http://tempuri.org/ICardV1Service/getCardListAllResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getCardListAllAsync(string em, QryptoCard.API.Admin.CardV1Service.vw_Card x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getCardPurchaseFilter", ReplyAction="http://tempuri.org/ICardV1Service/getCardPurchaseFilterResponse")]
        QryptoCard.API.Admin.CardV1Service.OutputModel getCardPurchaseFilter(string em, QryptoCard.API.Admin.CardV1Service.CardFilterModel fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getCardPurchaseFilter", ReplyAction="http://tempuri.org/ICardV1Service/getCardPurchaseFilterResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getCardPurchaseFilterAsync(string em, QryptoCard.API.Admin.CardV1Service.CardFilterModel fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getDepositTrxFilter", ReplyAction="http://tempuri.org/ICardV1Service/getDepositTrxFilterResponse")]
        QryptoCard.API.Admin.CardV1Service.OutputModel getDepositTrxFilter(string em, QryptoCard.API.Admin.CardV1Service.DepositFilterModel fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/getDepositTrxFilter", ReplyAction="http://tempuri.org/ICardV1Service/getDepositTrxFilterResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getDepositTrxFilterAsync(string em, QryptoCard.API.Admin.CardV1Service.DepositFilterModel fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/updateCardPrice", ReplyAction="http://tempuri.org/ICardV1Service/updateCardPriceResponse")]
        QryptoCard.API.Admin.CardV1Service.OutputModel updateCardPrice(string em, QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/updateCardPrice", ReplyAction="http://tempuri.org/ICardV1Service/updateCardPriceResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> updateCardPriceAsync(string em, QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/updateCardDepositFee", ReplyAction="http://tempuri.org/ICardV1Service/updateCardDepositFeeResponse")]
        QryptoCard.API.Admin.CardV1Service.OutputModel updateCardDepositFee(string em, QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardV1Service/updateCardDepositFee", ReplyAction="http://tempuri.org/ICardV1Service/updateCardDepositFeeResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> updateCardDepositFeeAsync(string em, QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICardV1ServiceChannel : QryptoCard.API.Admin.CardV1Service.ICardV1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardV1ServiceClient : System.ServiceModel.ClientBase<QryptoCard.API.Admin.CardV1Service.ICardV1Service>, QryptoCard.API.Admin.CardV1Service.ICardV1Service {
        
        public CardV1ServiceClient() {
        }
        
        public CardV1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardV1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardV1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardV1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QryptoCard.API.Admin.CardV1Service.OutputModel CardType(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x) {
            return base.Channel.CardType(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> CardTypeAsync(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x) {
            return base.Channel.CardTypeAsync(x);
        }
        
        public QryptoCard.API.Admin.CardV1Service.OutputModel getCardTypeById(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x) {
            return base.Channel.getCardTypeById(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getCardTypeByIdAsync(QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x) {
            return base.Channel.getCardTypeByIdAsync(x);
        }
        
        public QryptoCard.API.Admin.CardV1Service.OutputModel getActiveCard(string em) {
            return base.Channel.getActiveCard(em);
        }

        public System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getActiveCardAsync(string em) {
            return base.Channel.getActiveCardAsync(em);
        }

        public QryptoCard.API.Admin.CardV1Service.OutputModel getCardListAll(string em, QryptoCard.API.Admin.CardV1Service.vw_Card x) {
            return base.Channel.getCardListAll(em, x);
        }

        public System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getCardListAllAsync(string em, QryptoCard.API.Admin.CardV1Service.vw_Card x) {
            return base.Channel.getCardListAllAsync(em, x);
        }
        
        public QryptoCard.API.Admin.CardV1Service.OutputModel getCardPurchaseFilter(string em, QryptoCard.API.Admin.CardV1Service.CardFilterModel fil) {
            return base.Channel.getCardPurchaseFilter(em, fil);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getCardPurchaseFilterAsync(string em, QryptoCard.API.Admin.CardV1Service.CardFilterModel fil) {
            return base.Channel.getCardPurchaseFilterAsync(em, fil);
        }
        
        public QryptoCard.API.Admin.CardV1Service.OutputModel getDepositTrxFilter(string em, QryptoCard.API.Admin.CardV1Service.DepositFilterModel fil) {
            return base.Channel.getDepositTrxFilter(em, fil);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> getDepositTrxFilterAsync(string em, QryptoCard.API.Admin.CardV1Service.DepositFilterModel fil) {
            return base.Channel.getDepositTrxFilterAsync(em, fil);
        }
        
        public QryptoCard.API.Admin.CardV1Service.OutputModel updateCardPrice(string em, QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x) {
            return base.Channel.updateCardPrice(em, x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> updateCardPriceAsync(string em, QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x) {
            return base.Channel.updateCardPriceAsync(em, x);
        }
        
        public QryptoCard.API.Admin.CardV1Service.OutputModel updateCardDepositFee(string em, QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x) {
            return base.Channel.updateCardDepositFee(em, x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.CardV1Service.OutputModel> updateCardDepositFeeAsync(string em, QryptoCard.API.Admin.CardV1Service.tblM_Card_Type x) {
            return base.Channel.updateCardDepositFeeAsync(em, x);
        }
    }
}
