//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.API.Admin.AdminV1Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblM_Admin", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class tblM_Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BannedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateActivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateInvitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateJoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvitedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isVerifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminIDField, value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BannedBy {
            get {
                return this.BannedByField;
            }
            set {
                if ((object.ReferenceEquals(this.BannedByField, value) != true)) {
                    this.BannedByField = value;
                    this.RaisePropertyChanged("BannedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((this.CountryIDField.Equals(value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateActivated {
            get {
                return this.DateActivatedField;
            }
            set {
                if ((this.DateActivatedField.Equals(value) != true)) {
                    this.DateActivatedField = value;
                    this.RaisePropertyChanged("DateActivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateBanned {
            get {
                return this.DateBannedField;
            }
            set {
                if ((this.DateBannedField.Equals(value) != true)) {
                    this.DateBannedField = value;
                    this.RaisePropertyChanged("DateBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateInvited {
            get {
                return this.DateInvitedField;
            }
            set {
                if ((this.DateInvitedField.Equals(value) != true)) {
                    this.DateInvitedField = value;
                    this.RaisePropertyChanged("DateInvited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateJoin {
            get {
                return this.DateJoinField;
            }
            set {
                if ((this.DateJoinField.Equals(value) != true)) {
                    this.DateJoinField = value;
                    this.RaisePropertyChanged("DateJoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateVerified {
            get {
                return this.DateVerifiedField;
            }
            set {
                if ((this.DateVerifiedField.Equals(value) != true)) {
                    this.DateVerifiedField = value;
                    this.RaisePropertyChanged("DateVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvitedBy {
            get {
                return this.InvitedByField;
            }
            set {
                if ((object.ReferenceEquals(this.InvitedByField, value) != true)) {
                    this.InvitedByField = value;
                    this.RaisePropertyChanged("InvitedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profession {
            get {
                return this.ProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionField, value) != true)) {
                    this.ProfessionField = value;
                    this.RaisePropertyChanged("Profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterVia {
            get {
                return this.RegisterViaField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterViaField, value) != true)) {
                    this.RegisterViaField = value;
                    this.RaisePropertyChanged("RegisterVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleIDField, value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailURL {
            get {
                return this.ThumbnailURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailURLField, value) != true)) {
                    this.ThumbnailURLField = value;
                    this.RaisePropertyChanged("ThumbnailURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isBanned {
            get {
                return this.isBannedField;
            }
            set {
                if ((this.isBannedField.Equals(value) != true)) {
                    this.isBannedField = value;
                    this.RaisePropertyChanged("isBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isVerified {
            get {
                return this.isVerifiedField;
            }
            set {
                if ((this.isVerifiedField.Equals(value) != true)) {
                    this.isVerifiedField = value;
                    this.RaisePropertyChanged("isVerified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.AdminV1Service.tblM_Admin))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.AdminV1Service.vw_Admin))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_OTP))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.AdminV1Service.AdminFilterModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.AdminV1Service.PasswordChangeModel))]
    public partial class OutputModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblH_Admin_Login", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class tblH_Admin_Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMEIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isVerifyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminIDField, value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.AltitudeField, value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateExpired {
            get {
                return this.DateExpiredField;
            }
            set {
                if ((this.DateExpiredField.Equals(value) != true)) {
                    this.DateExpiredField = value;
                    this.RaisePropertyChanged("DateExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceName {
            get {
                return this.DeviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceNameField, value) != true)) {
                    this.DeviceNameField = value;
                    this.RaisePropertyChanged("DeviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceType {
            get {
                return this.DeviceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceTypeField, value) != true)) {
                    this.DeviceTypeField = value;
                    this.RaisePropertyChanged("DeviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMEI {
            get {
                return this.IMEIField;
            }
            set {
                if ((object.ReferenceEquals(this.IMEIField, value) != true)) {
                    this.IMEIField = value;
                    this.RaisePropertyChanged("IMEI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MEID {
            get {
                return this.MEIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MEIDField, value) != true)) {
                    this.MEIDField = value;
                    this.RaisePropertyChanged("MEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3 {
            get {
                return this.Param3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param3Field, value) != true)) {
                    this.Param3Field = value;
                    this.RaisePropertyChanged("Param3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isVerify {
            get {
                return this.isVerifyField;
            }
            set {
                if ((this.isVerifyField.Equals(value) != true)) {
                    this.isVerifyField = value;
                    this.RaisePropertyChanged("isVerify");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_Admin", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class vw_Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BannedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BannedByFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BannedByLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateActivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateInvitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateJoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvitedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvitedByFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvitedByLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isVerifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminIDField, value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BannedBy {
            get {
                return this.BannedByField;
            }
            set {
                if ((object.ReferenceEquals(this.BannedByField, value) != true)) {
                    this.BannedByField = value;
                    this.RaisePropertyChanged("BannedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BannedByFirstName {
            get {
                return this.BannedByFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BannedByFirstNameField, value) != true)) {
                    this.BannedByFirstNameField = value;
                    this.RaisePropertyChanged("BannedByFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BannedByLastName {
            get {
                return this.BannedByLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BannedByLastNameField, value) != true)) {
                    this.BannedByLastNameField = value;
                    this.RaisePropertyChanged("BannedByLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((this.CountryIDField.Equals(value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateActivated {
            get {
                return this.DateActivatedField;
            }
            set {
                if ((this.DateActivatedField.Equals(value) != true)) {
                    this.DateActivatedField = value;
                    this.RaisePropertyChanged("DateActivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateBanned {
            get {
                return this.DateBannedField;
            }
            set {
                if ((this.DateBannedField.Equals(value) != true)) {
                    this.DateBannedField = value;
                    this.RaisePropertyChanged("DateBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateInvited {
            get {
                return this.DateInvitedField;
            }
            set {
                if ((this.DateInvitedField.Equals(value) != true)) {
                    this.DateInvitedField = value;
                    this.RaisePropertyChanged("DateInvited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateJoin {
            get {
                return this.DateJoinField;
            }
            set {
                if ((this.DateJoinField.Equals(value) != true)) {
                    this.DateJoinField = value;
                    this.RaisePropertyChanged("DateJoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateVerified {
            get {
                return this.DateVerifiedField;
            }
            set {
                if ((this.DateVerifiedField.Equals(value) != true)) {
                    this.DateVerifiedField = value;
                    this.RaisePropertyChanged("DateVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvitedBy {
            get {
                return this.InvitedByField;
            }
            set {
                if ((object.ReferenceEquals(this.InvitedByField, value) != true)) {
                    this.InvitedByField = value;
                    this.RaisePropertyChanged("InvitedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvitedByFirstName {
            get {
                return this.InvitedByFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InvitedByFirstNameField, value) != true)) {
                    this.InvitedByFirstNameField = value;
                    this.RaisePropertyChanged("InvitedByFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvitedByLastName {
            get {
                return this.InvitedByLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InvitedByLastNameField, value) != true)) {
                    this.InvitedByLastNameField = value;
                    this.RaisePropertyChanged("InvitedByLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profession {
            get {
                return this.ProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionField, value) != true)) {
                    this.ProfessionField = value;
                    this.RaisePropertyChanged("Profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterVia {
            get {
                return this.RegisterViaField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterViaField, value) != true)) {
                    this.RegisterViaField = value;
                    this.RaisePropertyChanged("RegisterVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleIDField, value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailURL {
            get {
                return this.ThumbnailURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailURLField, value) != true)) {
                    this.ThumbnailURLField = value;
                    this.RaisePropertyChanged("ThumbnailURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isBanned {
            get {
                return this.isBannedField;
            }
            set {
                if ((this.isBannedField.Equals(value) != true)) {
                    this.isBannedField = value;
                    this.RaisePropertyChanged("isBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isVerified {
            get {
                return this.isVerifiedField;
            }
            set {
                if ((this.isVerifiedField.Equals(value) != true)) {
                    this.isVerifiedField = value;
                    this.RaisePropertyChanged("isVerified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblT_Admin_ForgotPassword", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class tblT_Admin_ForgotPassword : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isVerifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminIDField, value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedByField, value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3 {
            get {
                return this.Param3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param3Field, value) != true)) {
                    this.Param3Field = value;
                    this.RaisePropertyChanged("Param3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isVerified {
            get {
                return this.isVerifiedField;
            }
            set {
                if ((this.isVerifiedField.Equals(value) != true)) {
                    this.isVerifiedField = value;
                    this.RaisePropertyChanged("isVerified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblH_Admin_OTP", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class tblH_Admin_OTP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMEIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OTPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isVerifyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminIDField, value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.AltitudeField, value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateExpired {
            get {
                return this.DateExpiredField;
            }
            set {
                if ((this.DateExpiredField.Equals(value) != true)) {
                    this.DateExpiredField = value;
                    this.RaisePropertyChanged("DateExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceName {
            get {
                return this.DeviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceNameField, value) != true)) {
                    this.DeviceNameField = value;
                    this.RaisePropertyChanged("DeviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceType {
            get {
                return this.DeviceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceTypeField, value) != true)) {
                    this.DeviceTypeField = value;
                    this.RaisePropertyChanged("DeviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMEI {
            get {
                return this.IMEIField;
            }
            set {
                if ((object.ReferenceEquals(this.IMEIField, value) != true)) {
                    this.IMEIField = value;
                    this.RaisePropertyChanged("IMEI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MEID {
            get {
                return this.MEIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MEIDField, value) != true)) {
                    this.MEIDField = value;
                    this.RaisePropertyChanged("MEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantIDField, value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OTPID {
            get {
                return this.OTPIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OTPIDField, value) != true)) {
                    this.OTPIDField = value;
                    this.RaisePropertyChanged("OTPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3 {
            get {
                return this.Param3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param3Field, value) != true)) {
                    this.Param3Field = value;
                    this.RaisePropertyChanged("Param3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isVerify {
            get {
                return this.isVerifyField;
            }
            set {
                if ((this.isVerifyField.Equals(value) != true)) {
                    this.isVerifyField = value;
                    this.RaisePropertyChanged("isVerify");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminFilterModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    public partial class AdminFilterModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isVerifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isVerified {
            get {
                return this.isVerifiedField;
            }
            set {
                if ((this.isVerifiedField.Equals(value) != true)) {
                    this.isVerifiedField = value;
                    this.RaisePropertyChanged("isVerified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordChangeModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    public partial class PasswordChangeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminIDField, value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentPassword {
            get {
                return this.CurrentPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentPasswordField, value) != true)) {
                    this.CurrentPasswordField = value;
                    this.RaisePropertyChanged("CurrentPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminV1Service.IAdminV1Service")]
    public interface IAdminV1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/Login", ReplyAction="http://tempuri.org/IAdminV1Service/LoginResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel Login(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/Login", ReplyAction="http://tempuri.org/IAdminV1Service/LoginResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> LoginAsync(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/LoginVerify", ReplyAction="http://tempuri.org/IAdminV1Service/LoginVerifyResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel LoginVerify(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/LoginVerify", ReplyAction="http://tempuri.org/IAdminV1Service/LoginVerifyResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> LoginVerifyAsync(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/regenerateOTP", ReplyAction="http://tempuri.org/IAdminV1Service/regenerateOTPResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel regenerateOTP(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/regenerateOTP", ReplyAction="http://tempuri.org/IAdminV1Service/regenerateOTPResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> regenerateOTPAsync(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/viewAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/viewAdminResponse")]
        void viewAdmin(QryptoCard.API.Admin.AdminV1Service.vw_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/viewAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/viewAdminResponse")]
        System.Threading.Tasks.Task viewAdminAsync(QryptoCard.API.Admin.AdminV1Service.vw_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/forgotPassword", ReplyAction="http://tempuri.org/IAdminV1Service/forgotPasswordResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel forgotPassword(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/forgotPassword", ReplyAction="http://tempuri.org/IAdminV1Service/forgotPasswordResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> forgotPasswordAsync(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/checkForgotPassword", ReplyAction="http://tempuri.org/IAdminV1Service/checkForgotPasswordResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel checkForgotPassword(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/checkForgotPassword", ReplyAction="http://tempuri.org/IAdminV1Service/checkForgotPasswordResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> checkForgotPasswordAsync(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/changePassword", ReplyAction="http://tempuri.org/IAdminV1Service/changePasswordResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel changePassword(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/changePassword", ReplyAction="http://tempuri.org/IAdminV1Service/changePasswordResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> changePasswordAsync(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/getAdminFilter", ReplyAction="http://tempuri.org/IAdminV1Service/getAdminFilterResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel getAdminFilter(string em, QryptoCard.API.Admin.AdminV1Service.AdminFilterModel fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/getAdminFilter", ReplyAction="http://tempuri.org/IAdminV1Service/getAdminFilterResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> getAdminFilterAsync(string em, QryptoCard.API.Admin.AdminV1Service.AdminFilterModel fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/getAdminDetail", ReplyAction="http://tempuri.org/IAdminV1Service/getAdminDetailResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel getAdminDetail(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/getAdminDetail", ReplyAction="http://tempuri.org/IAdminV1Service/getAdminDetailResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> getAdminDetailAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/addAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/addAdminResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel addAdmin(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/addAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/addAdminResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> addAdminAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/getInvitedAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/getInvitedAdminResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel getInvitedAdmin(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/getInvitedAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/getInvitedAdminResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> getInvitedAdminAsync(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updateInvitedAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/updateInvitedAdminResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel updateInvitedAdmin(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updateInvitedAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/updateInvitedAdminResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updateInvitedAdminAsync(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/banAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/banAdminResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel banAdmin(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/banAdmin", ReplyAction="http://tempuri.org/IAdminV1Service/banAdminResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> banAdminAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/testEmail", ReplyAction="http://tempuri.org/IAdminV1Service/testEmailResponse")]
        void testEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/testEmail", ReplyAction="http://tempuri.org/IAdminV1Service/testEmailResponse")]
        System.Threading.Tasks.Task testEmailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/getAdminData", ReplyAction="http://tempuri.org/IAdminV1Service/getAdminDataResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel getAdminData(string em, string x);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/getAdminData", ReplyAction="http://tempuri.org/IAdminV1Service/getAdminDataResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> getAdminDataAsync(string em, string x);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updateAdminData", ReplyAction="http://tempuri.org/IAdminV1Service/updateAdminDataResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel updateAdminData(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updateAdminData", ReplyAction="http://tempuri.org/IAdminV1Service/updateAdminDataResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updateAdminDataAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updatePassword", ReplyAction="http://tempuri.org/IAdminV1Service/updatePasswordResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel updatePassword(string em, QryptoCard.API.Admin.AdminV1Service.PasswordChangeModel x);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updatePassword", ReplyAction="http://tempuri.org/IAdminV1Service/updatePasswordResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updatePasswordAsync(string em, QryptoCard.API.Admin.AdminV1Service.PasswordChangeModel x);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updateEmailOTP", ReplyAction="http://tempuri.org/IAdminV1Service/updateEmailOTPResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel updateEmailOTP(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updateEmailOTP", ReplyAction="http://tempuri.org/IAdminV1Service/updateEmailOTPResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updateEmailOTPAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updateEmail", ReplyAction="http://tempuri.org/IAdminV1Service/updateEmailResponse")]
        QryptoCard.API.Admin.AdminV1Service.OutputModel updateEmail(string em, QryptoCard.API.Admin.AdminV1Service.tblH_Admin_OTP x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminV1Service/updateEmail", ReplyAction="http://tempuri.org/IAdminV1Service/updateEmailResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updateEmailAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblH_Admin_OTP x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminV1ServiceChannel : QryptoCard.API.Admin.AdminV1Service.IAdminV1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminV1ServiceClient : System.ServiceModel.ClientBase<QryptoCard.API.Admin.AdminV1Service.IAdminV1Service>, QryptoCard.API.Admin.AdminV1Service.IAdminV1Service {
        
        public AdminV1ServiceClient() {
        }
        
        public AdminV1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminV1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminV1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminV1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel Login(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.Login(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> LoginAsync(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.LoginAsync(x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel LoginVerify(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login x) {
            return base.Channel.LoginVerify(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> LoginVerifyAsync(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login x) {
            return base.Channel.LoginVerifyAsync(x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel regenerateOTP(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login x) {
            return base.Channel.regenerateOTP(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> regenerateOTPAsync(QryptoCard.API.Admin.AdminV1Service.tblH_Admin_Login x) {
            return base.Channel.regenerateOTPAsync(x);
        }
        
        public void viewAdmin(QryptoCard.API.Admin.AdminV1Service.vw_Admin x) {
            base.Channel.viewAdmin(x);
        }
        
        public System.Threading.Tasks.Task viewAdminAsync(QryptoCard.API.Admin.AdminV1Service.vw_Admin x) {
            return base.Channel.viewAdminAsync(x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel forgotPassword(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.forgotPassword(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> forgotPasswordAsync(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.forgotPasswordAsync(x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel checkForgotPassword(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword x) {
            return base.Channel.checkForgotPassword(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> checkForgotPasswordAsync(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword x) {
            return base.Channel.checkForgotPasswordAsync(x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel changePassword(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword x) {
            return base.Channel.changePassword(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> changePasswordAsync(QryptoCard.API.Admin.AdminV1Service.tblT_Admin_ForgotPassword x) {
            return base.Channel.changePasswordAsync(x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel getAdminFilter(string em, QryptoCard.API.Admin.AdminV1Service.AdminFilterModel fil) {
            return base.Channel.getAdminFilter(em, fil);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> getAdminFilterAsync(string em, QryptoCard.API.Admin.AdminV1Service.AdminFilterModel fil) {
            return base.Channel.getAdminFilterAsync(em, fil);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel getAdminDetail(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin fil) {
            return base.Channel.getAdminDetail(em, fil);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> getAdminDetailAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin fil) {
            return base.Channel.getAdminDetailAsync(em, fil);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel addAdmin(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.addAdmin(em, x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> addAdminAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.addAdminAsync(em, x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel getInvitedAdmin(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.getInvitedAdmin(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> getInvitedAdminAsync(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.getInvitedAdminAsync(x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel updateInvitedAdmin(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.updateInvitedAdmin(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updateInvitedAdminAsync(QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.updateInvitedAdminAsync(x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel banAdmin(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.banAdmin(em, x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> banAdminAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.banAdminAsync(em, x);
        }
        
        public void testEmail() {
            base.Channel.testEmail();
        }
        
        public System.Threading.Tasks.Task testEmailAsync() {
            return base.Channel.testEmailAsync();
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel getAdminData(string em, string x) {
            return base.Channel.getAdminData(em, x);
        }

        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> getAdminDataAsync(string em, string x) {
            return base.Channel.getAdminDataAsync(em, x);
        }

        public QryptoCard.API.Admin.AdminV1Service.OutputModel updateAdminData(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.updateAdminData(em, x);
        }

        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updateAdminDataAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.updateAdminDataAsync(em, x);
        }

        public QryptoCard.API.Admin.AdminV1Service.OutputModel updatePassword(string em, QryptoCard.API.Admin.AdminV1Service.PasswordChangeModel x) {
            return base.Channel.updatePassword(em, x);
        }

        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updatePasswordAsync(string em, QryptoCard.API.Admin.AdminV1Service.PasswordChangeModel x) {
            return base.Channel.updatePasswordAsync(em, x);
        }

        public QryptoCard.API.Admin.AdminV1Service.OutputModel updateEmailOTP(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.updateEmailOTP(em, x);
        }

        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updateEmailOTPAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblM_Admin x) {
            return base.Channel.updateEmailOTPAsync(em, x);
        }
        
        public QryptoCard.API.Admin.AdminV1Service.OutputModel updateEmail(string em, QryptoCard.API.Admin.AdminV1Service.tblH_Admin_OTP x) {
            return base.Channel.updateEmail(em, x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.AdminV1Service.OutputModel> updateEmailAsync(string em, QryptoCard.API.Admin.AdminV1Service.tblH_Admin_OTP x) {
            return base.Channel.updateEmailAsync(em, x);
        }
    }
}
