//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.API.AuthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.ISecurityService")]
    public interface ISecurityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/validateUser", ReplyAction="http://tempuri.org/ISecurityService/validateUserResponse")]
        bool validateUser(string email, string passw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/validateUser", ReplyAction="http://tempuri.org/ISecurityService/validateUserResponse")]
        System.Threading.Tasks.Task<bool> validateUserAsync(string email, string passw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/validateAdmin", ReplyAction="http://tempuri.org/ISecurityService/validateAdminResponse")]
        bool validateAdmin(string email, string passw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/validateAdmin", ReplyAction="http://tempuri.org/ISecurityService/validateAdminResponse")]
        System.Threading.Tasks.Task<bool> validateAdminAsync(string email, string passw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/base64Encode", ReplyAction="http://tempuri.org/ISecurityService/base64EncodeResponse")]
        string base64Encode(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/base64Encode", ReplyAction="http://tempuri.org/ISecurityService/base64EncodeResponse")]
        System.Threading.Tasks.Task<string> base64EncodeAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/base64Decode", ReplyAction="http://tempuri.org/ISecurityService/base64DecodeResponse")]
        string base64Decode(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/base64Decode", ReplyAction="http://tempuri.org/ISecurityService/base64DecodeResponse")]
        System.Threading.Tasks.Task<string> base64DecodeAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/encryptapp", ReplyAction="http://tempuri.org/ISecurityService/encryptappResponse")]
        string encryptapp(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/encryptapp", ReplyAction="http://tempuri.org/ISecurityService/encryptappResponse")]
        System.Threading.Tasks.Task<string> encryptappAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/decryptapp", ReplyAction="http://tempuri.org/ISecurityService/decryptappResponse")]
        string decryptapp(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/decryptapp", ReplyAction="http://tempuri.org/ISecurityService/decryptappResponse")]
        System.Threading.Tasks.Task<string> decryptappAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/encryptdb", ReplyAction="http://tempuri.org/ISecurityService/encryptdbResponse")]
        string encryptdb(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/encryptdb", ReplyAction="http://tempuri.org/ISecurityService/encryptdbResponse")]
        System.Threading.Tasks.Task<string> encryptdbAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/decryptdb", ReplyAction="http://tempuri.org/ISecurityService/decryptdbResponse")]
        string decryptdb(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/decryptdb", ReplyAction="http://tempuri.org/ISecurityService/decryptdbResponse")]
        System.Threading.Tasks.Task<string> decryptdbAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/dbtoapp", ReplyAction="http://tempuri.org/ISecurityService/dbtoappResponse")]
        string dbtoapp(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/dbtoapp", ReplyAction="http://tempuri.org/ISecurityService/dbtoappResponse")]
        System.Threading.Tasks.Task<string> dbtoappAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/apptodb", ReplyAction="http://tempuri.org/ISecurityService/apptodbResponse")]
        string apptodb(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/apptodb", ReplyAction="http://tempuri.org/ISecurityService/apptodbResponse")]
        System.Threading.Tasks.Task<string> apptodbAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/signRSA", ReplyAction="http://tempuri.org/ISecurityService/signRSAResponse")]
        void signRSA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/signRSA", ReplyAction="http://tempuri.org/ISecurityService/signRSAResponse")]
        System.Threading.Tasks.Task signRSAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/decryptRSA", ReplyAction="http://tempuri.org/ISecurityService/decryptRSAResponse")]
        void decryptRSA(string txt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/decryptRSA", ReplyAction="http://tempuri.org/ISecurityService/decryptRSAResponse")]
        System.Threading.Tasks.Task decryptRSAAsync(string txt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServiceChannel : QryptoCard.API.AuthService.ISecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<QryptoCard.API.AuthService.ISecurityService>, QryptoCard.API.AuthService.ISecurityService {
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool validateUser(string email, string passw) {
            return base.Channel.validateUser(email, passw);
        }
        
        public System.Threading.Tasks.Task<bool> validateUserAsync(string email, string passw) {
            return base.Channel.validateUserAsync(email, passw);
        }
        
        public bool validateAdmin(string email, string passw) {
            return base.Channel.validateAdmin(email, passw);
        }
        
        public System.Threading.Tasks.Task<bool> validateAdminAsync(string email, string passw) {
            return base.Channel.validateAdminAsync(email, passw);
        }
        
        public string base64Encode(string str) {
            return base.Channel.base64Encode(str);
        }
        
        public System.Threading.Tasks.Task<string> base64EncodeAsync(string str) {
            return base.Channel.base64EncodeAsync(str);
        }
        
        public string base64Decode(string str) {
            return base.Channel.base64Decode(str);
        }
        
        public System.Threading.Tasks.Task<string> base64DecodeAsync(string str) {
            return base.Channel.base64DecodeAsync(str);
        }
        
        public string encryptapp(string str) {
            return base.Channel.encryptapp(str);
        }
        
        public System.Threading.Tasks.Task<string> encryptappAsync(string str) {
            return base.Channel.encryptappAsync(str);
        }
        
        public string decryptapp(string str) {
            return base.Channel.decryptapp(str);
        }
        
        public System.Threading.Tasks.Task<string> decryptappAsync(string str) {
            return base.Channel.decryptappAsync(str);
        }
        
        public string encryptdb(string str) {
            return base.Channel.encryptdb(str);
        }
        
        public System.Threading.Tasks.Task<string> encryptdbAsync(string str) {
            return base.Channel.encryptdbAsync(str);
        }
        
        public string decryptdb(string str) {
            return base.Channel.decryptdb(str);
        }
        
        public System.Threading.Tasks.Task<string> decryptdbAsync(string str) {
            return base.Channel.decryptdbAsync(str);
        }
        
        public string dbtoapp(string str) {
            return base.Channel.dbtoapp(str);
        }
        
        public System.Threading.Tasks.Task<string> dbtoappAsync(string str) {
            return base.Channel.dbtoappAsync(str);
        }
        
        public string apptodb(string str) {
            return base.Channel.apptodb(str);
        }
        
        public System.Threading.Tasks.Task<string> apptodbAsync(string str) {
            return base.Channel.apptodbAsync(str);
        }
        
        public void signRSA() {
            base.Channel.signRSA();
        }
        
        public System.Threading.Tasks.Task signRSAAsync() {
            return base.Channel.signRSAAsync();
        }
        
        public void decryptRSA(string txt) {
            base.Channel.decryptRSA(txt);
        }
        
        public System.Threading.Tasks.Task decryptRSAAsync(string txt) {
            return base.Channel.decryptRSAAsync(txt);
        }
    }
}
