//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT.Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_User
    {
        public long ID { get; set; }
        public string CompanyID { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string RoleID { get; set; }
        public string PIN { get; set; }
        public Nullable<long> CountryID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Profession { get; set; }
        public Nullable<System.DateTime> DateJoin { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public Nullable<int> isVerified { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<int> isBanned { get; set; }
        public Nullable<System.DateTime> DateInvited { get; set; }
        public string InvitedBy { get; set; }
        public Nullable<System.DateTime> DateBanned { get; set; }
        public string BannedBy { get; set; }
        public string RegisterVia { get; set; }
        public string ImageURL { get; set; }
        public string ThumbnailURL { get; set; }
        public Nullable<int> is2FA { get; set; }
        public Nullable<System.DateTime> Date2FA { get; set; }
    }
}
