//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT.Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_Setting_Counter
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Value { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
    }
}
