//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT.Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_Country_City
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string RegionCode { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
