//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.API.Admin.UserV1Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblM_User", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class tblM_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BannedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Date2FAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateActivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateInvitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateJoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvitedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> is2FAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isVerifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BannedBy {
            get {
                return this.BannedByField;
            }
            set {
                if ((object.ReferenceEquals(this.BannedByField, value) != true)) {
                    this.BannedByField = value;
                    this.RaisePropertyChanged("BannedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyIDField, value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((this.CountryIDField.Equals(value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date2FA {
            get {
                return this.Date2FAField;
            }
            set {
                if ((this.Date2FAField.Equals(value) != true)) {
                    this.Date2FAField = value;
                    this.RaisePropertyChanged("Date2FA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateActivated {
            get {
                return this.DateActivatedField;
            }
            set {
                if ((this.DateActivatedField.Equals(value) != true)) {
                    this.DateActivatedField = value;
                    this.RaisePropertyChanged("DateActivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateBanned {
            get {
                return this.DateBannedField;
            }
            set {
                if ((this.DateBannedField.Equals(value) != true)) {
                    this.DateBannedField = value;
                    this.RaisePropertyChanged("DateBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateInvited {
            get {
                return this.DateInvitedField;
            }
            set {
                if ((this.DateInvitedField.Equals(value) != true)) {
                    this.DateInvitedField = value;
                    this.RaisePropertyChanged("DateInvited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateJoin {
            get {
                return this.DateJoinField;
            }
            set {
                if ((this.DateJoinField.Equals(value) != true)) {
                    this.DateJoinField = value;
                    this.RaisePropertyChanged("DateJoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateVerified {
            get {
                return this.DateVerifiedField;
            }
            set {
                if ((this.DateVerifiedField.Equals(value) != true)) {
                    this.DateVerifiedField = value;
                    this.RaisePropertyChanged("DateVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvitedBy {
            get {
                return this.InvitedByField;
            }
            set {
                if ((object.ReferenceEquals(this.InvitedByField, value) != true)) {
                    this.InvitedByField = value;
                    this.RaisePropertyChanged("InvitedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profession {
            get {
                return this.ProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionField, value) != true)) {
                    this.ProfessionField = value;
                    this.RaisePropertyChanged("Profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterVia {
            get {
                return this.RegisterViaField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterViaField, value) != true)) {
                    this.RegisterViaField = value;
                    this.RaisePropertyChanged("RegisterVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleIDField, value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailURL {
            get {
                return this.ThumbnailURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailURLField, value) != true)) {
                    this.ThumbnailURLField = value;
                    this.RaisePropertyChanged("ThumbnailURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCard {
            get {
                return this.TotalCardField;
            }
            set {
                if ((this.TotalCardField.Equals(value) != true)) {
                    this.TotalCardField = value;
                    this.RaisePropertyChanged("TotalCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> is2FA {
            get {
                return this.is2FAField;
            }
            set {
                if ((this.is2FAField.Equals(value) != true)) {
                    this.is2FAField = value;
                    this.RaisePropertyChanged("is2FA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isBanned {
            get {
                return this.isBannedField;
            }
            set {
                if ((this.isBannedField.Equals(value) != true)) {
                    this.isBannedField = value;
                    this.RaisePropertyChanged("isBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isVerified {
            get {
                return this.isVerifiedField;
            }
            set {
                if ((this.isVerifiedField.Equals(value) != true)) {
                    this.isVerifiedField = value;
                    this.RaisePropertyChanged("isVerified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputModel", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT.Model.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.UserV1Service.tblM_User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.UserV1Service.vw_User_Commission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.UserV1Service.tblM_User_Commission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.UserV1Service.vw_User_Fee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QryptoCard.API.Admin.UserV1Service.tblM_User_Fee))]
    public partial class OutputModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_User_Commission", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class vw_User_Commission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CommissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommissionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Commission {
            get {
                return this.CommissionField;
            }
            set {
                if ((this.CommissionField.Equals(value) != true)) {
                    this.CommissionField = value;
                    this.RaisePropertyChanged("Commission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommissionID {
            get {
                return this.CommissionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CommissionIDField, value) != true)) {
                    this.CommissionIDField = value;
                    this.RaisePropertyChanged("CommissionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdated {
            get {
                return this.DateUpdatedField;
            }
            set {
                if ((this.DateUpdatedField.Equals(value) != true)) {
                    this.DateUpdatedField = value;
                    this.RaisePropertyChanged("DateUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedByField, value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3 {
            get {
                return this.Param3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param3Field, value) != true)) {
                    this.Param3Field = value;
                    this.RaisePropertyChanged("Param3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param4 {
            get {
                return this.Param4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param4Field, value) != true)) {
                    this.Param4Field = value;
                    this.RaisePropertyChanged("Param4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param5 {
            get {
                return this.Param5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param5Field, value) != true)) {
                    this.Param5Field = value;
                    this.RaisePropertyChanged("Param5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblM_User_Commission", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class tblM_User_Commission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CommissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommissionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Commission {
            get {
                return this.CommissionField;
            }
            set {
                if ((this.CommissionField.Equals(value) != true)) {
                    this.CommissionField = value;
                    this.RaisePropertyChanged("Commission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommissionID {
            get {
                return this.CommissionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CommissionIDField, value) != true)) {
                    this.CommissionIDField = value;
                    this.RaisePropertyChanged("CommissionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdated {
            get {
                return this.DateUpdatedField;
            }
            set {
                if ((this.DateUpdatedField.Equals(value) != true)) {
                    this.DateUpdatedField = value;
                    this.RaisePropertyChanged("DateUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedByField, value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3 {
            get {
                return this.Param3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param3Field, value) != true)) {
                    this.Param3Field = value;
                    this.RaisePropertyChanged("Param3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param4 {
            get {
                return this.Param4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param4Field, value) != true)) {
                    this.Param4Field = value;
                    this.RaisePropertyChanged("Param4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param5 {
            get {
                return this.Param5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param5Field, value) != true)) {
                    this.Param5Field = value;
                    this.RaisePropertyChanged("Param5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_User_Fee", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class vw_User_Fee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdated {
            get {
                return this.DateUpdatedField;
            }
            set {
                if ((this.DateUpdatedField.Equals(value) != true)) {
                    this.DateUpdatedField = value;
                    this.RaisePropertyChanged("DateUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedByField, value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeID {
            get {
                return this.FeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeIDField, value) != true)) {
                    this.FeeIDField = value;
                    this.RaisePropertyChanged("FeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3 {
            get {
                return this.Param3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param3Field, value) != true)) {
                    this.Param3Field = value;
                    this.RaisePropertyChanged("Param3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param4 {
            get {
                return this.Param4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param4Field, value) != true)) {
                    this.Param4Field = value;
                    this.RaisePropertyChanged("Param4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param5 {
            get {
                return this.Param5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param5Field, value) != true)) {
                    this.Param5Field = value;
                    this.RaisePropertyChanged("Param5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblM_User_Fee", Namespace="http://schemas.datacontract.org/2004/07/QryptoCard.INT")]
    [System.SerializableAttribute()]
    public partial class tblM_User_Fee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Param5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdated {
            get {
                return this.DateUpdatedField;
            }
            set {
                if ((this.DateUpdatedField.Equals(value) != true)) {
                    this.DateUpdatedField = value;
                    this.RaisePropertyChanged("DateUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedByField, value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeID {
            get {
                return this.FeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeIDField, value) != true)) {
                    this.FeeIDField = value;
                    this.RaisePropertyChanged("FeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1 {
            get {
                return this.Param1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param1Field, value) != true)) {
                    this.Param1Field = value;
                    this.RaisePropertyChanged("Param1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2 {
            get {
                return this.Param2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param2Field, value) != true)) {
                    this.Param2Field = value;
                    this.RaisePropertyChanged("Param2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3 {
            get {
                return this.Param3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param3Field, value) != true)) {
                    this.Param3Field = value;
                    this.RaisePropertyChanged("Param3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param4 {
            get {
                return this.Param4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param4Field, value) != true)) {
                    this.Param4Field = value;
                    this.RaisePropertyChanged("Param4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param5 {
            get {
                return this.Param5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Param5Field, value) != true)) {
                    this.Param5Field = value;
                    this.RaisePropertyChanged("Param5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserV1Service.IUserV1Service")]
    public interface IUserV1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/getUser", ReplyAction="http://tempuri.org/IUserV1Service/getUserResponse")]
        QryptoCard.API.Admin.UserV1Service.OutputModel getUser(QryptoCard.API.Admin.UserV1Service.tblM_User x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/getUser", ReplyAction="http://tempuri.org/IUserV1Service/getUserResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> getUserAsync(QryptoCard.API.Admin.UserV1Service.tblM_User x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/getUserCommissionList", ReplyAction="http://tempuri.org/IUserV1Service/getUserCommissionListResponse")]
        QryptoCard.API.Admin.UserV1Service.OutputModel getUserCommissionList(QryptoCard.API.Admin.UserV1Service.vw_User_Commission x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/getUserCommissionList", ReplyAction="http://tempuri.org/IUserV1Service/getUserCommissionListResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> getUserCommissionListAsync(QryptoCard.API.Admin.UserV1Service.vw_User_Commission x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/updateUserCommission", ReplyAction="http://tempuri.org/IUserV1Service/updateUserCommissionResponse")]
        QryptoCard.API.Admin.UserV1Service.OutputModel updateUserCommission(QryptoCard.API.Admin.UserV1Service.tblM_User_Commission x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/updateUserCommission", ReplyAction="http://tempuri.org/IUserV1Service/updateUserCommissionResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> updateUserCommissionAsync(QryptoCard.API.Admin.UserV1Service.tblM_User_Commission x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/getUserFeeList", ReplyAction="http://tempuri.org/IUserV1Service/getUserFeeListResponse")]
        QryptoCard.API.Admin.UserV1Service.OutputModel getUserFeeList(QryptoCard.API.Admin.UserV1Service.vw_User_Fee x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/getUserFeeList", ReplyAction="http://tempuri.org/IUserV1Service/getUserFeeListResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> getUserFeeListAsync(QryptoCard.API.Admin.UserV1Service.vw_User_Fee x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/updateUserFee", ReplyAction="http://tempuri.org/IUserV1Service/updateUserFeeResponse")]
        QryptoCard.API.Admin.UserV1Service.OutputModel updateUserFee(QryptoCard.API.Admin.UserV1Service.tblM_User_Fee x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserV1Service/updateUserFee", ReplyAction="http://tempuri.org/IUserV1Service/updateUserFeeResponse")]
        System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> updateUserFeeAsync(QryptoCard.API.Admin.UserV1Service.tblM_User_Fee x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserV1ServiceChannel : QryptoCard.API.Admin.UserV1Service.IUserV1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserV1ServiceClient : System.ServiceModel.ClientBase<QryptoCard.API.Admin.UserV1Service.IUserV1Service>, QryptoCard.API.Admin.UserV1Service.IUserV1Service {
        
        public UserV1ServiceClient() {
        }
        
        public UserV1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserV1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserV1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserV1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QryptoCard.API.Admin.UserV1Service.OutputModel getUser(QryptoCard.API.Admin.UserV1Service.tblM_User x) {
            return base.Channel.getUser(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> getUserAsync(QryptoCard.API.Admin.UserV1Service.tblM_User x) {
            return base.Channel.getUserAsync(x);
        }
        
        public QryptoCard.API.Admin.UserV1Service.OutputModel getUserCommissionList(QryptoCard.API.Admin.UserV1Service.vw_User_Commission x) {
            return base.Channel.getUserCommissionList(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> getUserCommissionListAsync(QryptoCard.API.Admin.UserV1Service.vw_User_Commission x) {
            return base.Channel.getUserCommissionListAsync(x);
        }
        
        public QryptoCard.API.Admin.UserV1Service.OutputModel updateUserCommission(QryptoCard.API.Admin.UserV1Service.tblM_User_Commission x) {
            return base.Channel.updateUserCommission(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> updateUserCommissionAsync(QryptoCard.API.Admin.UserV1Service.tblM_User_Commission x) {
            return base.Channel.updateUserCommissionAsync(x);
        }
        
        public QryptoCard.API.Admin.UserV1Service.OutputModel getUserFeeList(QryptoCard.API.Admin.UserV1Service.vw_User_Fee x) {
            return base.Channel.getUserFeeList(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> getUserFeeListAsync(QryptoCard.API.Admin.UserV1Service.vw_User_Fee x) {
            return base.Channel.getUserFeeListAsync(x);
        }
        
        public QryptoCard.API.Admin.UserV1Service.OutputModel updateUserFee(QryptoCard.API.Admin.UserV1Service.tblM_User_Fee x) {
            return base.Channel.updateUserFee(x);
        }
        
        public System.Threading.Tasks.Task<QryptoCard.API.Admin.UserV1Service.OutputModel> updateUserFeeAsync(QryptoCard.API.Admin.UserV1Service.tblM_User_Fee x) {
            return base.Channel.updateUserFeeAsync(x);
        }
    }
}
