//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT.Callback
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblH_Partner_Webhook_ID
    {
        public long ID { get; set; }
        public string Type { get; set; }
        public string Header { get; set; }
        public string TXID { get; set; }
        public string Request { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    }
}
