//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT.Callback
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_User_Balance
    {
        public long ID { get; set; }
        public string BalanceID { get; set; }
        public string UserID { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
