//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QryptoCard.INT.Callback
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_Card_Type_Recharge
    {
        public long CardTypeId { get; set; }
        public string Currency { get; set; }
        public string RechargeMinQuota { get; set; }
        public string RechargeMaxQuota { get; set; }
        public string RechargeFeeRate { get; set; }
        public string RechargeFee { get; set; }
        public Nullable<int> Digital { get; set; }
    }
}
